name: Test

on:
  push:
    branches:
      - main
    paths:
      - build.yaml
      - config.yaml
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**
  pull_request:
    branches:
      - main
    paths:
      - build.yaml
      - config.yaml
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build add-on
    strategy:
      matrix:
        arch: ["amd64", "aarch64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v5.0.0

      - name: Build add-on
        uses: home-assistant/builder@2025.09.0
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target /data/ \
            --addon

      - name: Image labels
        run: |
          docker inspect ghcr.io/lildude/ha-addon-teslamate-${{ matrix.arch }} --format='{{json .Config.Labels}}' | jq
