name: Test

on:
  push:
    branches:
      - main
    paths:
      - build.yaml
      - config.yaml
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**
  pull_request:
    branches:
      - main
    paths:
      - build.yaml
      - config.yaml
      - build.json
      - config.json
      - Dockerfile
      - rootfs/**

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build add-on
    strategy:
      matrix:
        arch: ["amd64", "armv7", "aarch64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7

      - name: Build add-on
        uses: home-assistant/builder@2024.08.2
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target /data/ \
            --addon

      - name: Image labels
        run: docker inspect ha-addon-teslamate/${{ matrix-arch }}-addon-teslamate:dev --format='{{json .Config.Labels}}' | jq
